### ISSUE TITLE
Add compatibility so that both URL path types are supported (absolute and relative)

### ISSUE THREAD

**Issue by suppadeliux** [meilisearch/docs-scraper#105]
Hello,

I am currently working on a documentation website generated with Jekyll, and Meilisearch has been pretty easy to add, with the docs-scraper and  the docs-searchbar.

In fact, I have many instances of my documentation website hosted in different places

That means that I have to run the docs-scraper for each site (update of repository).

I wish I could run only one scraper for all my sites, and be independent of where each documentation site is hosted. so my question is:

- Is it possible to replace absolute with relative URLs in docs-scraper?.

I guess, I can do that somehow overriding some of the logic from the source code of the scraper. But is there another way? (maybe someone else has already thought/discussed about that).

Thanks in advance!!

**Comment by curquiza** [comment]
For more documentation your can check out the README of this repo (docs-scraper)

**Comment by suppadeliux** [comment]
> Hello @suppadeliux!
> 
> Does the `start_urls` option work for your usecase?
> https://github.com/meilisearch/docs-scraper#start_urls
> You should be able to define the absolute URL in the array like:
> 
> ```shell
> {
>   "start_urls": ["https://www.mysite1.com", "https://www.mysite2.com"]
> }
> ```
> 
> Sorry if I miss understood your issue.
> 
> PS: I transfer your issue into the docs-scraper repo

Hello, and thanks for taking the time to answer to my question.

I have many `docs-scraper.config` files, each one containing the url for each documention website. Each time I run the scraper, I run it for each site. 

What I wish I could do is only run the scraper once, and having relative URLS on my index, instead of absolute. 

So When I will have the response from my meilisearch instance, I will only have relative paths (e.g. `/getting-started/introduction` or `about-us`) to redirect the user the the right result. This way, each of my documentation website, doesn't contain the raw URL on the search API response from another site.

I hope it clears it up a little bit :+1:

**Comment by curquiza** [comment]
I understand now. Unfortunately, and if I'm not wrong, there is no way to change the `url` field...
Once your documents are added to MeiliSearch, what you can do is to update all the `url` fields in your documents:
- you get all of them (using `offset`) with this route: https://docs.meilisearch.com/reference/api/documents.html#get-documents
- you update them with this route: https://docs.meilisearch.com/reference/api/documents.html#add-or-update-documents

We have many clients depending on your favorite language here to this update: https://github.com/meilisearch/integration-guides

**Comment by bidoubiwa** [comment]
We need a PR that add a compatibility with both path techniques. Thanks for raising this 🔥 Feel free to implement it otherwise we wait for a contributor to do so

**Comment by alallema** [comment]
As this repo is now low-maintenance, this PR is no longer relevant today. I'm closing all issues that are not bugs.
