### ISSUE TITLE
Browser Tests

### ISSUE THREAD

**Issue by sanders41** [meilisearch/docs-scraper#130]
The test suite needs to be run skipping any tests that uses chromedriver with `pipenv run pytest ./scraper/src -k "not _browser"`. Is this because the path is needed for the chrome driver? If that is the reason do you want them to be runnable? I could add an optional command line flag that lets you specify the path to the driver and make a fixture to set the environment variable which would make them runnable. Something like `pipenv run pytest ./scraper/src --chromedriver=/usr/local/bin/chromedriver`. The flag would be optional and wouldn't have to be set. This would allow browser tests to still be skipped as they are currently if someone doesn't have a chromedriver installed.

I'm also thinking the current browser tests aren't viable tests? I tried running them and most fail so I think if adding the flag for the driver path is something you want the tests would also need to be updated?

**Comment by bidoubiwa** [comment]
Adding the flag would be a first step in updating the tests to a working version. Thanks for figuring this out! 

I tried adding the chromedriver but tests kept failing with this error: 
```
 selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service
```
But when I used the same chromedriver to scrap locally the way you showed on the README.md it works great. I'm wondering what the problem could be.

**Comment by sanders41** [comment]
I think, but haven't verified yet, that is is because of the url that it is trying to scrape. For example [this test](https://github.com/meilisearch/docs-scraper/blob/7eed8fceeceb71aebb4023b0b12189bedd80d85d/scraper/src/tests/config_loader/open_selenium_browser_test.py#L31-L63) is trying to scrape `https://symfony.com/doc/(?P<version>.*?)/(?P<type_of_content>.*?)/`. Do you know of a page we could point it at to test (or maybe we could mock one?)? https://docs.meilisearch.com/ seems like the logical site if a live site is used, but I'm not sure how to recreate this url pattern there.

**Comment by sanders41** [comment]
After more thinking docs.meilisearch.com is static so maybe that's not the best sight to use.

**Comment by sanders41** [comment]
Here is where I am with some more looking into it. [test_extra_facets_should_be_set_from_start_urls_variables_browser](https://github.com/meilisearch/docs-scraper/blob/7eed8fceeceb71aebb4023b0b12189bedd80d85d/scraper/src/tests/config_loader/get_extra_facets_test.py#L14-L35) and [test_browser_not_needed_by_default](https://github.com/meilisearch/docs-scraper/blob/7eed8fceeceb71aebb4023b0b12189bedd80d85d/scraper/src/tests/config_loader/open_selenium_browser_test.py#L9-L14) (this one is not surprising since this one doesn't use chromedriver at all) are the two tests with browser that currently pass. All others fail right now.

There is an option to start running these two tests now and continue skipping the others if that is something you want to do. Instead of running the tests with `pipenv run pytest ./scraper/src -k "not _browser"` you could mark the browser tests and skip only the marked ones instead of all `_browser` tests. For example

```py
@pytest.mark.browser
@pytest.mark.usefixtures("chromedriver")
def test_extra_facets_should_be_set_from_start_urls_variables_with_two_start_url_browser(
        ...
```

Then you could run the tests with `pipenv run pytest -m "not browser" --chromedriver=/usr/local/bin/chromedriver" to skip this test.

Since technically some of the tests that do pass also use the browser, another option would be to mark the failing tests as `xfail` which means they are expected to fail and therefore don't fail the test run. The result would be like `85 passed, 5 xfailed` (passed are green and xfailed are yellow).

```py
@pytest.mark.xfail
@pytest.mark.usefixtures("chromedriver")
def test_extra_facets_should_be_set_from_start_urls_variables_with_two_start_url_browser(
        ...
```

These two options are only if you want to start running some browser tests now. Obviously another option is to leave things as they currently are until a full solution is found.

I do have a question that is a caveat to all of this. Is there a reason the tests are in the `src` directory? With the setup like this pytest doesn't find the `conftest.py` file which is needed for the flag and fixtures unless you first `cd` to the `./scraper/src` directory before running the tests. Moving the tests directory to the root of the project removes this issue, but I'm not sure if there is a reason they are in the src directory?

**Comment by sanders41** [comment]
I have all the tests except [test_browser_needed_when_config_contains_automatic_tag](https://github.com/meilisearch/docs-scraper/blob/4a821851103820a280cf51fce533e826fa95ea88/scraper/src/tests/config_loader/open_selenium_browser_test.py#L31-L63) working. Based on the name of the test I think it is saying that `js-render` should automatically set to true if needed or there is a value somewhere that makes it automatic, but I can't find anywhere that does this. Can you confirm that this is what is supposed to happen, and that is it possible without explicitly setting `js-render` to true? Or is that not a feature and therefore this test isn't possible?

If `js-render` needs to explicitly be set I need to make an update to the other test because they aren't setting this value. t looks to me like if `js-render` isn't set it will fall back to not using chromedriver. I did a quick test and the test will still work when setting this value, but wanted to make sure that is how thing should work first.

**Comment by bidoubiwa** [comment]
Hey @sanders41 yes I think moving the tests to the root is a good idea and also a good practice. How did you make the tests work? I'm curious to see what your solution was. Thanks a lot 🔥

**Comment by sanders41** [comment]
Sounds good. I'll finalize things and get it pushed soon. The main issue was the mocked `time.sleep`. Basically it was timing out before selenium had a chance to run. I removed that mock and the tests started passing.
