### ISSUE TITLE
Keep the settings of the previous index

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-scraper#14]
Currently, for performance reasons, each time the scraper runs, it deletes the index, creates a new one, adds [the default settings](https://github.com/meilisearch/docs-scraper/blob/32452e4af260c217254cec49097ae3bc31d8a556/scraper/src/meilisearch_helper.py#L50), and adds new documents (the content of the website).

Problem: if the user set up his/her own settings manually (for example, adding synonyms) the settings will be removed at each scraping. 
Currently, the config file does not provide any way to accept settings for MeiliSearch.

<s>A quick fix: keep the settings of the previous index, and apply them right after the default one.</s> _See the edit below_

In the future: provide a field in the config file to customize the settings of MeiliSearch.

### Why doing that right now?

We need to add synonyms in our own documentation: `relevancy` -> `relevant`

### Edit

I see that the config file is already ready to receive a `custom_settings` but the scraper does not use it. It might be better to use this field instead  😇

**Comment by Kerollmops** [comment]
Putting the setting before writing documents should be much faster!

**Comment by curquiza** [comment]
Oh good to know!
That's what we already do (lucky we are!) but I badly describe our process in this issue. I update it!
