### ISSUE TITLE
Upgrade python version to 3.8

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-scraper#16]
It's not currently possible to handle multiple python versions in the Pipfile -> https://github.com/pypa/pipenv/issues/1050

We should upgrade the python version of this package to 3.8

**Comment by renehernandez** [comment]
@curquiza  I will take a look at this

**Comment by renehernandez** [comment]
@curquiza Does this mean that the project will not support python version < 3.8? Should I update the [README](https://github.com/meilisearch/docs-scraper#from-source-code-) to mention python 3.8 as well, instead of python 3.6?

**Comment by curquiza** [comment]
@renehernandez! I've just updated the README! Thanks for noticing it 🙂
