### ISSUE TITLE
Implement "selector_rank"

### ISSUE THREAD

**Issue by edi9999** [meilisearch/docs-scraper#162]
**Description**

Currently, there is a way to add rank between pages

```
{
  "start_urls": [
    {
      "url": "http://www.example.com/docs/concepts/",
      "page_rank": 5
    },
    {
      "url": "http://www.example.com/docs/contributors/",
      "page_rank": 1
    }
  ]
}
```

Documented here :

https://github.com/meilisearch/docs-scraper#using-page-rank-

I have a usecase where my pages do not have different page rank, but rather some content on the page has more significance than other.

I would like to be able to rank the content with selectors.

**Basic example**

```
<h1>My website</h1>

<h2>Reasons</h2>
<p class="introduction">FoobarFoobarFoobarFoobarFoobarFoobarFoobar</p>

<h2>Other things</h2>
 <p>Details</p>
```

In this case, I know that the content that is inside the "introduction" paragraph is more important than the other content at the end, and I would like my search results to reflect that.

I'm thinking of using something like this for the config : 

```
{
  "selectors": {
    "lvl1": "h1",
    "lvl2": "h2",
    "text": [ 
            { 
                "rank": 5,
                "selector": "p.introduction"
            },
            { 
                "rank": 1,
                "selector": "p:not(.introduction)"
            },
    ]
}
```

**Other**

This is a real problem I have, on my website, the CHANGELOG and README of my software is on the same page, and results from the CHANGELOG sometimes come before results from the README. The results from the README should be prioritized.

Maybe the API could be different, instead of adding an array inside the selectors, one could use : 

```
"selector_ranks":   [ 
            { 
                "rank": 5,
                "selector": "p.introduction"
            }
    ]
```

And simply use "p" for the "text" selector.

**Comment by edi9999** [comment]
@bidoubiwa any update on this ?

**Comment by bidoubiwa** [comment]
Hello @edi9999 sorry for the delay with the hacktoberfest I have been very busy. 

### Text ranking suggestion

I very much like the idea. I would keep both the possibility to declare it using a string (current behavior) and your suggestion with an array. The same way it works for some other options in the config file.


### Selector rank

> This is a real problem I have, on my website, the CHANGELOG and README of my software is on the same page, and results from the CHANGELOG sometimes come before results from the README. The results from the README should be prioritized.

I'm not sure why this problem can not be fixed with your previous suggestion. 

```
{
  "selectors": {
    "lvl1": "h1",
    "lvl2": "h2",
    "text": [ 
            { 
                "rank": 5,
                "selector": "p.readme"
            },
            { 
                "rank": 1,
                "selector": "p.contributing"
            },
    ]
}
```

I think I need some clarification on this suggestion before I can confirm your last suggestion.

**Comment by edi9999** [comment]
Hello @bidoubiwa , thanks for the reply !

It was not very clear in my previous message, I just meant to say that the problem that I showed with the `<h1>My website</h1>...` was a simplified example to explain the problem. I also wanted to say that I have exactly the same problem (with probably just some more complex selectors on my real production website.

For the last suggestion, I wanted to ask if you prefered this version : 

**V_Selector_Ranks**

```
{
  "selectors": {
    "lvl1": "h1",
    "lvl2": "h2",
    "text": "p.readme, p.contributing",
   },
   "selector_ranks":   [ 
            { 
                "rank": 5,
                "selector": "p.readme"
            },
            { 
                "rank": 1,
                "selector": "p.contributing"
            }
    ]
}
```

or this version
**V_Selector_Arrays** : 

```
{
  "selectors": {
    "lvl1": "h1",
    "lvl2": "h2",
    "text": [ 
            { 
                "rank": 5,
                "selector": "p.readme"
            },
            { 
                "rank": 1,
                "selector": "p.contributing"
            },
    ]
}
```

But I think you already made clear that you like **V_Selector_Arrays**

**Comment by bidoubiwa** [comment]
Yes, I think `V_Selector_Arrays` is very clear! Also, it doesn't separate concerns which could create fields that are depending on another one. 

If you want to implement this it would be a very nice addition :)

**Comment by edi9999** [comment]
I plan to do it, but not right now, I also have a lot of things going on.

**Comment by bidoubiwa** [comment]
Okey! No problem :) Thanks anyway

**Comment by alallema** [comment]
As this repo is now low-maintenance, this PR is no longer relevant today. I'm closing all issues that are not bugs.
