### ISSUE TITLE
Remove nb_hits update in config file

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-scraper#17]
Since we don't use this metric (we indeed don't update the config file and push it to GitHub after updating it) we should remove the file update in the code.

But I think it's still interesting to keep the final prompt that says:
```bash
Nb hits: XXX
```

**Comment by renehernandez** [comment]
@curquiza I am going to take a look at this next

**Comment by renehernandez** [comment]
I took a look at the codebase and we can solve it with removing this line: https://github.com/meilisearch/docs-scraper/blob/master/scraper/src/index.py#L106

Optionally, we could remove all the code related with updating the number of hits:

* `update_nb_hits_value` function at https://github.com/meilisearch/docs-scraper/blob/master/scraper/src/config/config_loader.py#L131
* `NbHitsUpdater` class at https://github.com/meilisearch/docs-scraper/blob/master/scraper/src/config/nb_hits_updater.py

**Comment by curquiza** [comment]
It looks ok for me 🙂
Keep in mind we still want the prompt in the terminal indicating the number of hits at the end. Maybe it would imply to extract some code of these parts.

**Comment by renehernandez** [comment]
> It looks ok for me 🙂
> Keep in mind we still want the prompt in the terminal indicating the number of hits at the end. Maybe it would imply to extract some code of these parts.

The number of hits is obtained from the `DocumentationSpider.NB_INDEXED` field. I'll double check anyways
