### ISSUE TITLE
CI jobs are failing

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-scraper#170]
The jobs in the CI are failing 
- linter-check
- unit-tests
- integration-tests

https://github.com/meilisearch/docs-scraper/actions/runs/1445509929

**Comment by brunoocasali** [comment]
Since the tests are working in the last actions, I suppose this could be closed! 

<img width="908" alt="image" src="https://user-images.githubusercontent.com/4116980/153085583-ceb44219-6934-4d21-94e9-d273be1e2cd2.png">
