### ISSUE TITLE
Update index without downtime

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/docs-scraper#219]
Swap indexes without downtime.

Currently is not possible in Meilisearch but as soon as it is we need to implement it here.

The roadmap idea is here: https://roadmap.meilisearch.com/c/65-swap-index

**Comment by curquiza** [comment]
Something already discussed on the product side here: https://github.com/meilisearch/product/discussions/79
This is something I'm waiting for a long time personally haha

**Comment by alallema** [comment]
As this repo is now low-maintenance, this PR is no longer relevant today. I'm closing all issues that are not bugs.
