### ISSUE TITLE
Missing 'requests' module?

### ISSUE THREAD

**Issue by Karlostavitch1** [meilisearch/docs-scraper#255]
**Description**
I am testing the docs-scraper on my Synology NAS, and the container stops immediately with the error listed below.

**Expected behavior**
Scrape some sites

**Current behavior**
container immediately stops on error.

**Screenshots or Logs**
File "./docs_scraper", line 5, in <module>
from scraper.src.index import run_config
File "/docs-scraper/scraper/src/index.py", line 7, in <module>
import requests

**Environment (please complete the following information):**
Synology DSM 7.1 running Docker
docs-scaper v0.12.3 docker image (getmeili/docs-scraper:v0.12.3)

**Comment by Karlostavitch1** [comment]
my bad, didn't run the scraper in the pip environment as per the docker execution commend.

**Comment by alallema** [comment]
Hi @Karlostavitch1,
No problem, thanks for closing the PR 😃
