### ISSUE TITLE
Update `path to the config file` example in the Readme

### ISSUE THREAD

**Issue by mdubus** [meilisearch/docs-scraper#263]
## What's wrong?

Inside the Readme, we have the following example on the [Run the scraper section](https://github.com/meilisearch/docs-scraper#from-source-code-) indicating `<path-to-your-config-file>`:

`pipenv run ./docs_scraper <path-to-your-config-file>`

But then, we can find these examples: 

`<path-to-your-config-file>` is now `config.json` in the  [with Docker section](https://github.com/meilisearch/docs-scraper#with-docker-)

```docker run -t --rm \
    -e MEILISEARCH_HOST_URL=<your-meilisearch-host-url> \
    -e MEILISEARCH_API_KEY=<your-meilisearch-api-key> \
    -v <absolute-path-to-your-config-file>:/docs-scraper/config.json \
    getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
```

Same in the [In a GitHub Action section](https://github.com/meilisearch/docs-scraper#in-a-github-action-) with the following example: 

```
       docker run -t --rm \
          -e MEILISEARCH_HOST_URL=$HOST_URL \
          -e MEILISEARCH_API_KEY=$API_KEY \
          -v $CONFIG_FILE_PATH:/docs-scraper/config.json \
          getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json
```

## Solution

We should rename the `config.json` occurrences with `<path-to-your-config-file>`

**Comment by abhishak3** [comment]
I would love to take up this issue. Can you please assign it to me?

**Comment by mdubus** [comment]
Hello @abhishak3 👋

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/docs-scraper/blob/main/CONTRIBUTING.md).
We are looking forward to reviewing your PR.
