### ISSUE TITLE
Add an explanation about the config file name inside the Readme

### ISSUE THREAD

**Issue by mdubus** [meilisearch/docs-scraper#264]
## What's wrong

By reading the Readme from top to bottom, we are given [an example of config file](https://github.com/meilisearch/docs-scraper/issues/263) but it is not clear in which file we have to put this.

The information can be found below in an other section (the config file can be anything as it is passed as an argument later), but the information is arriving later than what we would expect.

## Solution

Explain [inside the config file paragraph](https://github.com/meilisearch/docs-scraper/issues/263) that the config file name can be anything and doesn't matter.

**Comment by abhishak3** [comment]
I would like to contribute to this issue. Please assign me.
