### ISSUE TITLE
Add analytics to repo

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-scraper#286]
Related to https://github.com/meilisearch/integration-guides/issues/150

This require to also
- [x] Add the version of docs-scraper following [this example](https://github.com/meilisearch/meilisearch-python/blob/main/meilisearch/version.py)
- [x] Add in the CONTRIBUTING guide the requirement to update the version following [this example](https://github.com/meilisearch/meilisearch-python/blob/main/meilisearch/version.py)
- [x] Add a check of version script in a`.workflow/script` dir following [this example](https://github.com/meilisearch/meilisearch-python/blob/main/.github/scripts/check-release.sh)
- [x] Add  in `publish-docker-latest.yml` and in `publish-docker-tag.yml` the check-release script following [this example](https://github.com/meilisearch/meilisearch-python/blob/main/.github/workflows/pypi-publish.yml) but remove the `pypi` part inside this

**Comment by gmourier** [comment]
Hello @bidoubiwa!

Do you think we could have it live during the following days?

**Comment by bidoubiwa** [comment]
@alallema can tell you. But she is on holliday

**Comment by brunoocasali** [comment]
@gmourier, I assume you want to understand the user behavior by measuring how many people are using this, right?
This is not @alallema's priority, but we could make it work earlier based on your thoughts.

**Comment by gmourier** [comment]
Exactly @brunoocasali; sorry for not having precise that at first @bidoubiwa. 

I aim to start collecting usage as soon as possible to have quantitative data to rely on for the scrapper/crawler product. This is just one aspect of the decision-making process but it seems to be a quick-win to get some knowledge
