### ISSUE TITLE
Create image version that works in arm environments

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-scraper#288]
Currently, the [image from the docker hub](https://hub.docker.com/layers/getmeili/docs-scraper/latest/images/sha256-9848a93f7ad02bda927dbe6e0d7d0013778449ce367e45a81744e82c63218732?context=explore) only works in an amd environment. Nonetheless, we should be compatible with arm as well. 

TODO:
- [x]  Update [publish-docker-latest](https://github.com/meilisearch/docs-scraper/blob/main/.github/workflows/publish-docker-latest.yml), following the example of the [docker CI](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-docker-images.yml) of meilisearch. Note that we do not need the corn trigger nor the `Send CI information to Cloud team`.
- [x] Remove [publish-docker-tag.yml](https://github.com/meilisearch/docs-scraper/blob/main/.github/workflows/publish-docker-tag.yml)
- [ ] Update the README accordingly, explaining how to run in both env using docker

**Comment by brunoocasali** [comment]
Why do we need this step?

> update the release drafter so that it creates two release drafts, one for amd one for arm.

**Comment by bidoubiwa** [comment]
You'r right, they could be done in the same release. Let me update the description

**Comment by brunoocasali** [comment]
> Update the README accordingly, explaining how to run in both env using docker

I don't think this could be applied because the change did not impact in the way we "run" the code, we just added a new image architecture in the dockerhub.
