### ISSUE TITLE
Run the integration tests also on the builded docker images

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-scraper#289]
Recently we got an issue with a mismatch of chromedriver between the version of Python or docker image was using and the one required from `selenium` (I suppose), see #284.

This is bound to happen again and no tests are ran to ensure we have no mismatch.
Thus, we should add a test ensuring that our docker images are working.

**Comment by brunoocasali** [comment]
No new problem has happened ever since I'm closing this!
