### ISSUE TITLE
Wrong command line usage in Contributing.md

### ISSUE THREAD

**Issue by renehernandez** [meilisearch/docs-scraper#49]
In the [development workflow section](https://github.com/meilisearch/docs-scraper/blob/master/CONTRIBUTING.md#development-workflow) of the Contributing.md file, it says the following:

```bash
$ pipenv install
$ pipenv run ./docs_scraper run <path-to-your-config-file>
```

The line:

```bash
$ pipenv run ./docs_scraper run <path-to-your-config-file>
```
has an extra run argument after the path to `./docs_scraper`

It should be instead:

```bash
$ pipenv run ./docs_scraper <path-to-your-config-file>
```

**Comment by eskombro** [comment]
You are right! Well spotted @renehernandez thanks!
