### ISSUE TITLE
Fail to create Docker Image for since python 3.8 is used

### ISSUE THREAD

**Issue by curquiza** [meilisearch/docs-scraper#54]
<img width="1313" alt="Capture d’écran 2020-07-20 à 15 59 08" src="https://user-images.githubusercontent.com/20380692/87946224-070c9800-caa2-11ea-8a2c-8dd91bb196e1.png">

See this [job](https://github.com/meilisearch/docs-scraper/runs/890089558?check_suite_focus=true)

**Comment by renehernandez** [comment]
I think it would be nice to push to docker hub a prerelease version after every PR merged on master. That would help catch these issues before actually producing a release.
As a side benefit, it would allow folks to use the prerelease image to test on real scenarios

**Comment by curquiza** [comment]
As a first step, I will add a test that builds a docker image on each PR, at least to test the docker image can be built.
